FROM python:3.6.5-slim

# install netcat
RUN apt-get update \
  && apt-get -y install netcat \
  && apt-get clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Celery context is the same with module web

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add app
COPY . /usr/src/app

# add entrypoint.sh
COPY ./entrypoint-celery-worker.sh /usr/src/app/entrypoint-celery-worker.sh

# run server
CMD ["./entrypoint-celery-worker.sh"]
